#!/usr/bin/env sh

root="$(realpath "${1:-.}")"
exec="$(realpath "$0")"
sandbox="$(dirname "$exec")/sandbox"

log() {
	>&2 printf '%s\n' "$@"
}

log "> Running ${exec} in directory ${root}."

cd "$root" || exit 2
if [ -e setup ] ; then
	sh setup || exit 1
fi

find . -maxdepth 1 -type f -name '*.test' | while IFS= read -r filename; do
	name="$(basename "${filename%.*}")"
	test="$(realpath "$filename")"
	log "> Running test file ${filename} (name=${name}, abspath=${test})."

	sh "$sandbox" "$name" < "$test" || exit 1

done || exit 1

find . -maxdepth 1 -type d | while IFS= read -r directory; do
	if [ "$directory" = '.' ] ; then continue ; fi
	if [ -e "${directory}/run" ] ; then
		sh "${directory}/run" "${directory}" || exit 1
	else
		sh "$exec" "${directory}" || exit 1
	fi
done || exit 1

if [ -e teardown ] ; then
	sh teardown || exit 1
fi
