#!/usr/bin/env sh

name="$1"

scratch="$(mktemp --tmpdir --directory "memoize-test-cli_${name}.XXXXXXXX")"
mkdir "${scratch}/sandbox"
mkdir "${scratch}/cache"
mkdir "${scratch}/files"

log() {
	>&2 echo "$@"
}

log "> Running sandbox ${scratch}/sandbox"
cd "${scratch}/sandbox" || exit 2

eval_last_cmd() {
	if [ -n "$cmd" ] ; then
		eval "$cmd" 1>"${scratch}/files/${cmdno}-stdout-got" 2>"${scratch}/files/${cmdno}-stderr-got"
		rc="$?"
		diff "${scratch}/files/${cmdno}-stdout-expected" "${scratch}/files/${cmdno}-stdout-got" || exit 1
		diff "${scratch}/files/${cmdno}-stderr-expected" "${scratch}/files/${cmdno}-stderr-got" || exit 1
		if [ "$ret" = "FAIL" ] ; then
			test "$rc" -ne 0 || exit 1
		else
			test "$rc" -eq "$ret" || exit 1
		fi
	fi
}

export MEMOIZE_CACHE="${scratch}/cache"
lineno=0
while IFS= read -r line; do
	lineno=$((lineno+1))

	printf "%s\n" "$line"
	case "$line" in
		\$*)
			eval_last_cmd
			cmdno="$lineno"
			ret="$(sed 's/.* --> \(.*\)/\1/g' <<< "$line")"
			if [ "$ret" != "$line" ] ; then
				cmd="$(sed 's/\$ \(.*\) --> .*/\1/g' <<< "$line")"
			else
				ret=0
				cmd="$(sed 's/\$ \(.*\)/\1/g' <<< "$line")"
			fi
			touch "${scratch}/files/${cmdno}-stdout-expected"
			touch "${scratch}/files/${cmdno}-stderr-expected"
			;;
		\#*)
			# Ignore comments.
			;;
		\>\&2*)
			stderr="$(sed 's/>&2 \(.*\)/\1/g' <<< "$line")"
			printf "%s\n" "$stderr" >> "${scratch}/files/${cmdno}-stderr-expected"
			;;
		\>\&1*)
			stdout="$(sed 's/>&1 \(.*\)/\1/g' <<< "$line")"
			printf "%s\n" "$stdout" >> "${scratch}/files/${cmdno}-stdout-expected"
			;;
		*)
			printf "%s\n" "$line" >> "${scratch}/files/${cmdno}-stdout-expected"
			;;
	esac

done

eval_last_cmd

log "> Exiting sandbox ${scratch}/sandbox"
cd "$OLDPWD" || exit 2
rm -rf "$scratch"
