[package]
name = "memoize"
version = "0.1.0"
authors = ["Aurélien Ooms <aurelien.ooms@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tempfile = "3.6.0"
memoize_lib = { path = "../memoize_lib" }
