#!/usr/bin/env sh

: "${MEMOIZE_CACHE:="${XDG_CACHE_HOME:-"$HOME/.cache"}/memoize"}"
validity="$1"
shift

cache="${MEMOIZE_CACHE}/$(memoize-args-key "$@")"

O="${cache}/O"
E="${cache}/E"
R="${cache}/R"
T="${cache}/T"

now=$(date +%s)
if [ -e "$O" ]; then
	previous=$(cat "$T")
	x=$((previous + validity - now))
else
	mkdir -p "$cache"
	x=-1
fi

if [ $x -lt 0 ]; then
	eval "$@" 1>"$O" 2>"$E"
	echo "$?" > "$R"
	echo "$now" > "$T"
fi

cat "$O"
cat "$E" >&2
exit "$(cat "$R")"
