#!/usr/bin/env sh

# fault tolerant version of memoize

: ${MEMOIZE_CACHE:="${XDG_CACHE_HOME:-"$HOME/.cache"}/memoize"}
validity="$1"
shift

tmp=$(mktemp /tmp/.memoize_XXXXXXXXXX)

for a in "$@" ; do
	printf '%s\0' "$a" >> "$tmp"
done

cache="${MEMOIZE_CACHE}/$(sha1sum "$tmp" | head -c 40)"

O="${cache}/O"
E="${cache}/E"
R="${cache}/R"
T="${cache}/T"

now=$(date +%s)
if [ -e "$O" ]; then
	previous=$(cat "$T")
	x=$((previous + validity - now))
else
	mkdir -p "$cache"
	touch "$O"
	echo 0 > "$T"
	x=-1
fi

if [ $x -lt 0 ]; then
	eval "$@" 1>"$tmp" 2>"$E"
	rc="$?"
	if [ "$rc" -eq 0 ]; then
		cp "$tmp" "$O"
		echo "$now" > "$T"
	fi
	echo "$rc" > "$R"
fi

rm "$tmp"

cat "$O"
cat "$E" >&2
exit "$(cat "$R")"
