#!/usr/bin/env sh

# retrieves memoized value if not older that "$1" seconds
# use "$1"=-1 to bypass the validity check

: ${MEMOIZE_CACHE:="${XDG_CACHE_HOME:-"$HOME/.cache"}/memoize"}
validity="$1"
shift

cache="${MEMOIZE_CACHE}/$(memoize-args-key "$@")"

O="${cache}/O"
E="${cache}/E"
R="${cache}/R"
T="${cache}/T"

if [ ! -e "$O" ]; then
	echo "no entry for '$*'" >&2
	exit 1
fi

if [ "$validity" -ge 0 ]; then

	now=$(date +%s)
	previous=$(cat "$T")
	x=$((previous + validity - now))

	if [ "$x" -lt 0 ]; then
		echo "entry expired for '$*'" >&2
		exit 2
	fi

fi

cat "$O"
cat "$E" >&2
exit "$(cat "$R")"
