#!/usr/bin/env sh

# fault tolerant version of memoize

: ${MEMOIZE_CACHE:="${XDG_CACHE_HOME:-"$HOME/.cache"}/memoize"}
validity="$1"
shift

cache="${MEMOIZE_CACHE}/$(memoize-args-key "$@")"

O="${cache}/O"
E="${cache}/E"
R="${cache}/R"
T="${cache}/T"

now=$(date +%s)
if [ -e "$O" ]; then
	previous=$(cat "$T")
	x=$((previous + validity - now))
else
	mkdir -p "$cache"
	touch "$O"
	echo 0 > "$T"
	x=-1
fi

if [ $x -lt 0 ]; then
	tmp=$(mktemp --tmpdir "${USER}-memoize.XXXXXXXXXX")
	eval "$@" 1>"$tmp" 2>"$E"
	rc="$?"
	if [ "$rc" -eq 0 ]; then
		cp "$tmp" "$O"
		echo "$now" > "$T"
	fi
	echo "$rc" > "$R"
	rm "$tmp"
fi


cat "$O"
cat "$E" >&2
exit "$(cat "$R")"
