#!/usr/bin/env sh

tmp=$(mktemp /tmp/.memoize_XXXXXXXXXX)

for a in "$@" ; do
	printf '%s\0' "$a" >> "$tmp"
done

cache="$HOME/.cache/memoize/$(sha1sum "$tmp" | head -c 40)"
rm "$tmp"

rm -rf "$cache"
